input {
  file{
    path => "/Users/saimanikantatelagamsetty/Downloads/GitDemo-microservice_communication/ELKstack.log"
    start_position=> "beginning"
  }
}

output {

  stdout{
    codec => rubydebug
  }
  elasticsearch {
    hosts => [ "http://localhost:9200" ]
    index => "microservice-logs"
  }
}
